version: '3.8'

services:
#  user-service:
#    build: user-service
#    container_name: user-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/localmart-dev
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=secret
#    networks:
#      - user-network

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=localmart-dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-network

networks:
  user-network:

volumes:
  postgres_data:
